name: Release APK Build

on:
  release:
    types: [published]

jobs:
  build:
    permissions:
      contents: write
      actions: write
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease

      - name: Generate Temporary Keystore
        run: |
          keytool -genkeypair -v -keystore temp-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass tempstorepass -keypass tempkeypass -alias tempkey -dname "CN=Temporary, OU=Temporary, O=Temporary, L=Temporary, S=Temporary, C=US"

      - name: Sign APK with Temporary Keystore
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore temp-keystore.jks \
            -storepass tempstorepass \
            -keypass tempkeypass \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            tempkey

      - name: Align APK
        run: |
          $ANDROID_HOME/build-tools/<build-tools-version>/zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release-signed.apk

      - name: Upload Signed APK to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release-signed.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
