name: Release APK Build

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug

      - name: Align APK
        run: $ANDROID_HOME/build-tools/31.0.0/zipalign -v 4 \
          app/build/outputs/apk/debug/app-debug.apk \
          app/build/outputs/apk/debug/app-debug-aligned.apk

      - name: Upload APK to release
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug-aligned.apk

      - name: Attach APK to GitHub release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug-aligned.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
